version: '3.9'
services:
  # MongoDB services
  mongo_db:
    container_name: natours-db
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
# Node API service
  api:  
    build: .
    ports:
      - 3000:3000
    environment: 
      PORT: 3000
      MONGODB_URI: mongodb://natours-db:27017
      DB_NAME: natours-db
      NAME: Natours  
    depends_on:
      - mongo_db
volumes: 
  mongo_db: {}